filegroup(
    name = "sql_schema",
    srcs = ["sql/schema.sql"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sql_migration",
    srcs = glob(["sql/*/*.sql"]),
    visibility = ["//visibility:public"],
)
