name: CI2

on:
  workflow_dispatch: # Allow manual runs.
  pull_request:
    branches: ["develop"]
  push:
    branches: ["develop"]

jobs:
  ci:
    name: CI2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Build and test
        run: |
          set -ex
          bazel build --platforms=@zig_sdk//platform:linux_amd64 //...
          bazel test --platforms=@zig_sdk//platform:linux_amd64 //...
